### ISSUE TITLE
Blank window with QT

### ISSUE THREAD

**Issue by ZhiyuZhang** [xinglunju/tdviz#1]
Hi Xing, 

After I upgraded to Catalina OS 10.15, I re-installed anaconda3 and tdviz. 
It seems that tdvis is not working well, by showing an incomplete manual panel and a blank window. 

I found the following solution: 
pip install PyQt5 
pip install PyQt5-sip

These will solve the problem. 
Just let you know about it. 

Cheers,
Zhiyu

**Comment by xinglunju** [comment]
> Hi Xing,
> 
> After I upgraded to Catalina OS 10.15, I re-installed anaconda3 and tdviz.
> It seems that tdvis is not working well, by showing an incomplete manual panel and a blank window.
> 
> I found the following solution:
> pip install PyQt5
> pip install PyQt5-sip
> 
> These will solve the problem.
> Just let you know about it.
> 
> Cheers,
> Zhiyu

Many thanks! I will add a note in the README file.
